AWSTemplateFormatVersion: 2010-09-09
Description: AWS EC2 Instance.

Parameters:
   MyKeyName:
      Description: Select the keyName from the list
      Type: AWS::EC2::KeyPair::KeyName

Resources:
   DevMyEC2Instance:
      Type: AWS::EC2::Instance
      Properties:
         ImageId: ami-0d9462a653c34dab7
         InstanceType: t2.micro
         KeyName: !Ref MyKeyName
         SecurityGroups:
            - default 
            - !Ref SSHSecurityGroup  
   SSHSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
         GroupDescription: my new SSH SG
         SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp: 0.0.0.0/0      