AWSTemplateFormatVersion: 2010-09-09
Description: AZ EC2 Instance.

Paramerters:
   MyKeyName:
      Description: Select the keyName from the list
      Type: AWS::EC2::KeyPari::KeyName
   MyAvailabilityZone:
      Description: Select the AZ
      Type: String
      Default: ap-south-1
      AllowedValues:
         - ap-south-1
         - ap-south-2
         - ap-south-3

Resources:
   DevMyEC2Instance:
      Type: AWS::EC2::Instance
      Properties:
         ImageId:
         InstanceType: t2.micro
         KeyName: !Ref MyKeyName
         SecurityGroups:
            - default 
            - !Ref SSHSecurityGroup
         AvailabilityZone: !Ref MyAvailabilityZone  
   SSHSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
         GroupDescription: my new SSH SG
         SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp: 0.0.0.0/0      